name: Validate HACS
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Download repo
        with:
          fetch-depth: 0

      - name: HACS Action
        uses: hacs/action@main
        with:
          CATEGORY: integration
          ignore: brands