name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip hydro_imgw dir
        run: |
          cd /home/runner/work/Home-Assistant-custom-components-Hydro-IMGW/Home-Assistant-custom-components-Hydro-IMGW/custom_components/hydro_imgw
          zip hydro_imgw.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Home-Assistant-custom-components-Hydro-IMGW/Home-Assistant-custom-components-Hydro-IMGW/custom_components/froggy/hydro_imgw.zip
          asset_name: hydro_imgw.zip
          tag: ${{ github.ref }}
          overwrite: true